# Generated by Django 4.2.2 on 2024-11-24 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('video', models.FileField(blank=True, null=True, upload_to='courses/videos/')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='courses/pdfs/')),
            ],
        ),
    ]
