# Generated by Django 4.2 on 2024-11-26 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('exercises', models.TextField()),
                ('sample_codes', models.TextField()),
                ('project_ideas', models.TextField()),
                ('frameworks', models.CharField(max_length=255)),
            ],
        ),
    ]
